load("//tools:defs.bzl", "goo_cc_library")

# Makefile:83 AST_SRCS.
goo_cc_library(
    name = "ast",
    srcs = [
        "ast.c",
        "ast_constructors.c",
    ],
    strict_hdrs = True,
    visibility = ["//visibility:public"],
    deps = [
        "//include:ast_h",
    ],
)
