load("//tools:defs.bzl", "goo_cc_library")

# Makefile:94 PACKAGE_SRCS.
goo_cc_library(
    name = "package",
    srcs = ["import_resolver.c"],
    visibility = ["//src/types:__pkg__"],
    deps = [
        "//include:import_resolver_h",
    ],
)
