load("//tools:defs.bzl", "goo_cc_library")

# Makefile:87 ERROR_SRCS.
goo_cc_library(
    name = "errors",
    srcs = ["error.c"],
    visibility = ["//visibility:public"],
    deps = [
        "//include:error_h",
    ],
)
