#!/bin/bash
# alloc-doors probe: Goo-visible heap memory must come from ONE door.
#
# Why this exists. The ARC header-feasibility audit (docs/superpowers/specs/
# 2026-07-28-arc-header-feasibility-audit.md) found a live asymmetry: a slice's
# backing store was allocated by a RAW calloc in goo_slice_alloc but grown by
# goo_realloc. That works today only because both are bare libc calls. Under
# ANY scheme that puts a header in front of the payload — a refcount for ARC, or
# a region tag — goo_realloc would offset a pointer that never had a header, and
# corrupt the heap.
#
# So the invariant is structural, and it is worth asserting before the header
# exists rather than debugging it afterwards: inside runtime.c, only goo_alloc,
# goo_realloc and goo_free may name a libc allocator.
#
# SCOPE. runtime.c only. Deliberately NOT the whole runtime:
#   - arena.c allocates its own BLOCKS with malloc. Those are the region's
#     backing store, never a Goo object, and they must stay raw.
#   - platform.c and io.c own private buffers that never become Goo values.
#   - concurrency.c/channels.c allocate scheduler and channel internals.
# Those are listed in the audit as known exemptions. If Goo-visible allocation
# ever moves into one of them, add it here and to the audit together.

#
# SECOND DOOR (2026-08-08): strdup across all of src/.
#
# The runtime scan above is about a HEADER offset. This one is about an
# unchecked NULL. include/xalloc.h swept fixed-size allocations to xmalloc and
# xcalloc, and its own header comment says variable-sized ones were left alone
# "where recovery or graceful degradation matters". strdup fell through that
# gap and nothing caught it: 570 call sites, and a measurement on 2026-08-08
# found that NOT ONE of them checked the result. A failed strdup put a NULL in
# a struct field, to be dereferenced later with no context left to report.
#
# So xstrdup exists now, and this scan keeps the bare name out. Ban the NAME,
# not the allocation: unlike the runtime scan there is no function whitelist,
# because there is no legitimate raw strdup left in src/.
#
# Run the controls with --self-test. A scan that cannot report an offender is
# not a gate.

set -u

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/src/runtime/runtime.c"

fail() { echo "alloc-doors-probe: FAIL — $1"; exit 1; }

# --------------------------------------------------------------------------
# The strdup scan, factored out so --self-test can aim it at a scratch tree.
# Prints one line per offender and returns them on stdout.
#
# EXEMPTIONS, both deliberate:
#   src/parser/parser.tab.c    generated by bison, not edited by hand
#   src/types/dependent_types.c  carries `#define strdup str_dup`, a portability
#                              shim whose own str_dup already handles NULL. It
#                              is outside GOO_SRCS (quarantined by P5.6), so it
#                              is not in the shipped compiler either way.
# --------------------------------------------------------------------------
scan_strdup() {
    local root="$1"
    ( cd "$root" && find src -type f \( -name '*.c' -o -name '*.h' \) \
        ! -path 'src/parser/parser.tab.c' \
        ! -path 'src/types/dependent_types.c' \
        -print0 2>/dev/null | xargs -0 awk '
      # Skip whole-line comments, matching the runtime scan below: a doc comment
      # may legitimately NAME strdup while explaining why the code stopped
      # calling it.
      /^[[:space:]]*(\/\/|\*|\/\*)/ { next }
      # Bare strdup only. The leading character class is what stops this from
      # matching xstrdup, which is the approved door.
      /(^|[^_[:alnum:]])strdup[[:space:]]*\(/ { printf "  %s:%d  %s\n", FILENAME, FNR, $0 }
    ' 2>/dev/null )
}

# --------------------------------------------------------------------------
# --self-test: prove the scan reports BOTH answers on demand.
#
# Controls 3 and 4 are the load-bearing ones. Controls 1 and 2 alone are also
# satisfied by a scan that is bluntly broken in either direction — one that
# always passes, or one that flags every line. Control 3 requires it to IGNORE
# the approved form and control 4 requires it to IGNORE a comment, so neither
# blunt failure can produce the full set.
# --------------------------------------------------------------------------
self_test() {
    local rc=0 tmp n
    tmp="$(mktemp -d)"
    trap 'rm -rf "$tmp"' RETURN
    mkdir -p "$tmp/src/probe"

    echo "=== alloc-doors-probe --self-test ==="

    echo "=== Control 1: clean file -> 0 offenders ==="
    printf 'char *a = xmalloc(4);\n' > "$tmp/src/probe/p.c"
    n=$(scan_strdup "$tmp" | wc -l)
    echo "  got: $n"
    [ "$n" -eq 0 ] || { echo "  CONTROL 1 FAILED"; rc=1; }

    echo "=== Control 2: one raw strdup -> 1 offender ==="
    printf 'char *a = strdup(s);\n' > "$tmp/src/probe/p.c"
    n=$(scan_strdup "$tmp" | wc -l)
    echo "  got: $n"
    [ "$n" -eq 1 ] || { echo "  CONTROL 2 FAILED (a scan that never fires would print 0)"; rc=1; }

    echo "=== Control 3: xstrdup is the approved door -> 0 offenders ==="
    printf 'char *a = xstrdup(s);\nchar *b = xstrdup(t);\n' > "$tmp/src/probe/p.c"
    n=$(scan_strdup "$tmp" | wc -l)
    echo "  got: $n"
    [ "$n" -eq 0 ] || { echo "  CONTROL 3 FAILED (scan matches the x-prefixed form)"; rc=1; }

    echo "=== Control 4: strdup named in a comment -> 0 offenders ==="
    printf '// strdup(s) is banned here\n/* strdup(s) too */\n' > "$tmp/src/probe/p.c"
    n=$(scan_strdup "$tmp" | wc -l)
    echo "  got: $n"
    [ "$n" -eq 0 ] || { echo "  CONTROL 4 FAILED (scan flags comments)"; rc=1; }

    echo "=== Control 5: exempt files are not scanned -> 0 offenders ==="
    mkdir -p "$tmp/src/parser" "$tmp/src/types"
    printf 'char *a = xmalloc(4);\n' > "$tmp/src/probe/p.c"
    printf 'char *a = strdup(s);\n' > "$tmp/src/parser/parser.tab.c"
    printf 'char *a = strdup(s);\n' > "$tmp/src/types/dependent_types.c"
    n=$(scan_strdup "$tmp" | wc -l)
    echo "  got: $n"
    [ "$n" -eq 0 ] || { echo "  CONTROL 5 FAILED (exemption list not applied)"; rc=1; }

    if [ "$rc" -eq 0 ]; then
        echo "alloc-doors-probe --self-test: TEETH CONFIRMED (5/5 controls)"
    else
        echo "alloc-doors-probe --self-test: TEETH MISSING"
    fi
    return "$rc"
}

[ "${1:-}" = "--self-test" ] && { self_test; exit $?; }

[ -f "$SRC" ] || fail "missing $SRC"

echo "=== alloc-doors-probe: one allocation door for Goo-visible memory ==="

# Every line in runtime.c that names a libc allocator, with its function.
# awk tracks the enclosing top-level function by its opening line.
# Comment lines are skipped: several doc comments legitimately NAME calloc
# while explaining why the code no longer calls it.
offenders="$(awk '
  /^[[:space:]]*(\/\/|\*|\/\*)/ { next }
  /^[A-Za-z_].*\)[[:space:]]*\{[[:space:]]*$/ { fn=$0; sub(/\(.*/,"",fn); sub(/.*[[:space:]\*]/,"",fn) }
  /(^|[^_[:alnum:]])(malloc|calloc|realloc|free)[[:space:]]*\(/ {
    if (fn != "goo_alloc" && fn != "goo_realloc" && fn != "goo_free")
      printf "  %s:%d  in %s()  ->  %s\n", "runtime.c", NR, fn, $0
  }
' "$SRC")"

if [ -n "$offenders" ]; then
    echo "$offenders"
    fail "a libc allocator is named outside goo_alloc/goo_realloc/goo_free"
fi

echo "  runtime.c: only goo_alloc, goo_realloc and goo_free name a libc allocator"

# --------------------------------------------------------------------------
# Second door: no bare strdup anywhere in src/. See the header comment.
# --------------------------------------------------------------------------
strdup_offenders="$(scan_strdup "$ROOT")"
if [ -n "$strdup_offenders" ]; then
    echo "$strdup_offenders" | head -20
    n="$(printf '%s\n' "$strdup_offenders" | wc -l | tr -d ' ')"
    [ "$n" -gt 20 ] && echo "  ... and $((n - 20)) more"
    fail "$n raw strdup call site(s) in src/ — use xstrdup (include/xalloc.h)"
fi

echo "  src/: no bare strdup — every string copy goes through xstrdup"
echo "alloc-doors-probe: PASS"
