load("//tools:defs.bzl", "goo_cc_library")

# Makefile:81 LEXER_SRCS.
goo_cc_library(
    name = "lexer",
    srcs = [
        "lexer.c",
        "token.c",
    ],
    visibility = ["//visibility:public"],
)
