#!/usr/bin/env python3
"""Emit Bazel probe targets from the Makefile's probe recipes.

WHY GENERATED. There are 186 probe gates. Hand-writing 63 target declarations
produces a diff nobody can review, and a hand edit that drifts from its recipe
is invisible. Generating them makes the BUILD file a derivation, and
tests/probes/targets_current.sh gates that it is current.

WHY IT REFUSES TO GUESS. The parse below is an INFERENCE about what a recipe
asserts, and a systematically wrong inference produces confidently green tests
rather than an error. So every recipe that does not match the narrow shape this
understands is OMITTED and printed to stderr with a reason. Silent omission
would be the worst outcome: a gate that looks migrated and is not.

Four probes were already known to need this before it was written:

  asi-gocompat-probe   22 printf cases, not one fixture
  arc-release-probe    24 fixtures in one recipe
  readline-probe       pipes stdin, and uses a .probe_expected.txt sidecar
  osargs-probe         passes argv to the built binary

Usage: gen_probe_targets.py <census-file> > tests/probes/generated.bzl
"""
import re
import subprocess
import sys

MAKEFILE = "Makefile"

# Fixtures that cannot pass until phase 3c brings NNG in.
NNG_FIXTURES = {
    "far_shim_probe", "lanes_allreduce_probe", "lanes_jacobi_probe",
    "lanes_monomorphize_probe", "lanes_partition_probe",
    "lanes_repartition_probe", "lanes_stencil_probe",
    "lanes_stencilstep_probe", "lanes_stencilstep_r2_probe",
}


def recipe(gate):
    out = subprocess.run(
        ["awk", "-v", "p=^%s:" % gate,
         "$0~p{f=1;next} f&&/^[^\\t]/{exit} f", MAKEFILE],
        capture_output=True, text=True)
    return out.stdout


def parse(gate, body):
    """Return (target_dict, None) or (None, reason-for-omission)."""
    if "printf" in body:
        return None, "generates source or input with printf"
    # stdin INTO THE BUILT BINARY only. `wc -l < build/x.actual.txt` is a
    # shell redirect in an assertion, not input to the program under test.
    if re.search(r"\./build/\S+\s*<", body):
        return None, "pipes stdin into the built binary"

    srcs = sorted(set(re.findall(r"examples/([a-z0-9_]+)\.goo", body)))
    if not srcs:
        return None, "compiles no examples/*.goo"
    if len(srcs) > 1:
        return None, "references %d fixtures, not one" % len(srcs)
    src = srcs[0]

    if re.search(r"rc -eq 0|-x build/", body):
        # A compile-reject probe. Extract the diagnostic it demands: the
        # grep -q that is NOT the LLVM-verifier guard.
        msgs = re.findall(r'grep -q[iEF]* +"([^"]+)"', body)
        msgs = [m for m in msgs
                if "Module verification" not in m and "LLVM ERROR" not in m]
        msgs = [m for m in msgs if "|" not in m]  # a regex alternation is not a fixed string
        if len(msgs) != 1:
            return None, "reject probe with %d extractable diagnostics" % len(msgs)
        return {"gate": gate, "name": gate.replace("-", "_"), "src": src,
                "reject": True, "stderr": msgs[0], "nng": False}, None

    exps = sorted(set(re.findall(r"examples/([a-z0-9_.]+\.txt)", body)))
    exps = [e for e in exps if e.endswith("expected.txt")]
    if len(exps) != 1:
        return None, "found %d expected files, need exactly one" % len(exps)
    exp = exps[0]
    if exp != src + ".expected.txt".replace(".goo", ""):
        # accept the standard <src>.expected.txt only
        if exp != "%s.expected.txt" % src:
            return None, "non-standard expected sidecar '%s'" % exp

    # argv passed to the built binary would change what runs. A redirect
    # (`> out.txt`) is not an argument -- the first version of this rule read
    # one as an argument and omitted 48 of 80 probes.
    if re.search(r"\./build/\S+\s+(?![<>|&])\S", body):
        return None, "passes arguments to the built binary"

    return {"gate": gate, "name": gate.replace("-", "_"), "src": src,
            "expected": exp, "reject": False,
            "nng": src in NNG_FIXTURES}, None


def main():
    census = sys.argv[1] if len(sys.argv) > 1 else "tests/probes/census.txt"
    wanted = []
    for line in open(census):
        cat, gate = line.split()
        if cat in ("golden", "example"):
            wanted.append(gate)

    targets, omitted = [], []
    for gate in wanted:
        t, why = parse(gate, recipe(gate))
        (targets.append(t) if t else omitted.append((gate, why)))

    print('"""GENERATED by tools/gen_probe_targets.py -- do not edit.')
    print("")
    print("Regenerate with:")
    print("    python3 tools/gen_probe_targets.py tests/probes/census.txt \\")
    print("        > tests/probes/generated.bzl")
    print("")
    print("tests/probes/targets_current.sh gates that this file is current.")
    print('"""')
    print("")
    print('load("//tools:goo_probe.bzl", "goo_probe", "goo_reject_probe")')
    print("")
    print("def generated_probes():")
    print('    """%d probes generated from the Makefile."""' % len(targets))
    for t in targets:
        if t.get("reject"):
            print("    goo_reject_probe(")
            print('        name = "%s",' % t["name"])
            print('        src = "//examples:%s.goo",' % t["src"])
            print('        stderr_contains = "%s",' % t["stderr"].replace('"', '\\"'))
            print("    )")
            continue
        print("    goo_probe(")
        print('        name = "%s",' % t["name"])
        print('        src = "//examples:%s.goo",' % t["src"])
        print('        expected = "//examples:%s",' % t["expected"])
        if t["nng"]:
            print('        # Needs the far transport, so it needs NNG: phase 3c.')
            print('        tags = ["manual"],')
        print("    )")
    if not targets:
        print("    pass")

    for gate, why in omitted:
        print("OMITTED %-28s %s" % (gate, why), file=sys.stderr)
    print("generated %d targets, omitted %d of %d"
          % (len(targets), len(omitted), len(wanted)), file=sys.stderr)


if __name__ == "__main__":
    main()
