"""GENERATED by tools/gen_probe_targets.py -- do not edit.

Regenerate with:
    python3 tools/gen_probe_targets.py tests/probes/census.txt \
        > tests/probes/generated.bzl

tests/probes/targets_current.sh gates that this file is current.
"""

load("//tools:goo_probe.bzl", "goo_probe")

def generated_probes():
    """45 probes generated from the Makefile."""
    goo_probe(
        name = "append_probe",
        src = "//examples:append_probe.goo",
        expected = "//examples:append_probe.expected.txt",
    )
    goo_probe(
        name = "baseline_probe",
        src = "//examples:baseline_probe.goo",
        expected = "//examples:baseline_probe.expected.txt",
    )
    goo_probe(
        name = "block_scope_probe",
        src = "//examples:block_scope_probe.goo",
        expected = "//examples:block_scope_probe.expected.txt",
    )
    goo_probe(
        name = "break_nested_probe",
        src = "//examples:break_nested.goo",
        expected = "//examples:break_nested.expected.txt",
    )
    goo_probe(
        name = "break_probe",
        src = "//examples:break_probe.goo",
        expected = "//examples:break_probe.expected.txt",
    )
    goo_probe(
        name = "cap_probe",
        src = "//examples:cap_probe.goo",
        expected = "//examples:cap_probe.expected.txt",
    )
    goo_probe(
        name = "chan_elem_probe",
        src = "//examples:chan_elem_probe.goo",
        expected = "//examples:chan_elem_probe.expected.txt",
    )
    goo_probe(
        name = "chan_padded_probe",
        src = "//examples:chan_padded_probe.goo",
        expected = "//examples:chan_padded_probe.expected.txt",
    )
    goo_probe(
        name = "chan_probe",
        src = "//examples:chan_probe.goo",
        expected = "//examples:chan_probe.expected.txt",
    )
    goo_probe(
        name = "chan_uint_probe",
        src = "//examples:chan_uint_probe.goo",
        expected = "//examples:chan_uint_probe.expected.txt",
    )
    goo_probe(
        name = "charlit_probe",
        src = "//examples:charlit_probe.goo",
        expected = "//examples:charlit_probe.expected.txt",
    )
    goo_probe(
        name = "commaok_probe",
        src = "//examples:commaok_probe.goo",
        expected = "//examples:commaok_probe.expected.txt",
    )
    goo_probe(
        name = "conststr_nul_probe",
        src = "//examples:conststr_nul_probe.goo",
        expected = "//examples:conststr_nul_probe.expected.txt",
    )
    goo_probe(
        name = "conststr_probe",
        src = "//examples:conststr_probe.goo",
        expected = "//examples:conststr_probe.expected.txt",
    )
    goo_probe(
        name = "continue_probe",
        src = "//examples:continue_probe.goo",
        expected = "//examples:continue_probe.expected.txt",
    )
    goo_probe(
        name = "conv_probe",
        src = "//examples:conv_probe.goo",
        expected = "//examples:conv_probe.expected.txt",
    )
    goo_probe(
        name = "enum_probe",
        src = "//examples:enum_ctor_probe.goo",
        expected = "//examples:enum_ctor_probe.expected.txt",
    )
    goo_probe(
        name = "erru_abi_probe",
        src = "//examples:erru_abi_probe.goo",
        expected = "//examples:erru_abi_probe.expected.txt",
    )
    goo_probe(
        name = "erru_catch_probe",
        src = "//examples:erru_catch_probe.goo",
        expected = "//examples:erru_catch_probe.expected.txt",
    )
    goo_probe(
        name = "erru_error_probe",
        src = "//examples:erru_error_probe.goo",
        expected = "//examples:erru_error_probe.expected.txt",
    )
    goo_probe(
        name = "escape_probe",
        src = "//examples:escape_probe.goo",
        expected = "//examples:escape_probe.expected.txt",
    )
    goo_probe(
        name = "escape_range_probe",
        src = "//examples:escape_range_probe.goo",
        expected = "//examples:escape_range_probe.expected.txt",
    )
    goo_probe(
        name = "file_io_probe",
        src = "//examples:file_io_probe.goo",
        expected = "//examples:file_io_probe.expected.txt",
    )
    goo_probe(
        name = "go_probe",
        src = "//examples:go_probe.goo",
        expected = "//examples:go_probe.expected.txt",
    )
    goo_probe(
        name = "guard_probe",
        src = "//examples:guard_probe.goo",
        expected = "//examples:guard_probe.expected.txt",
    )
    goo_probe(
        name = "hexesc_probe",
        src = "//examples:hexesc_probe.goo",
        expected = "//examples:hexesc_probe.expected.txt",
    )
    goo_probe(
        name = "int64_probe",
        src = "//examples:int64_probe.goo",
        expected = "//examples:int64_probe.expected.txt",
    )
    goo_probe(
        name = "lvalue_probe",
        src = "//examples:lvalue_probe.goo",
        expected = "//examples:lvalue_probe.expected.txt",
    )
    goo_probe(
        name = "m10_probe",
        src = "//examples:m10_probe.goo",
        expected = "//examples:m10_probe.expected.txt",
    )
    goo_probe(
        name = "map_probe",
        src = "//examples:map_probe.goo",
        expected = "//examples:map_probe.expected.txt",
    )
    goo_probe(
        name = "match_probe",
        src = "//examples:match_probe.goo",
        expected = "//examples:match_probe.expected.txt",
    )
    goo_probe(
        name = "methods_probe",
        src = "//examples:methods_probe.goo",
        expected = "//examples:methods_probe.expected.txt",
    )
    goo_probe(
        name = "new_probe",
        src = "//examples:new_probe.goo",
        expected = "//examples:new_probe.expected.txt",
    )
    goo_probe(
        name = "nullable_abi_probe",
        src = "//examples:nullable_abi_probe.goo",
        expected = "//examples:nullable_abi_probe.expected.txt",
    )
    goo_probe(
        name = "nullable_assign_probe",
        src = "//examples:nullable_assign_probe.goo",
        expected = "//examples:nullable_assign_probe.expected.txt",
    )
    goo_probe(
        name = "nullable_iflet_probe",
        src = "//examples:nullable_iflet_probe.goo",
        expected = "//examples:nullable_iflet_probe.expected.txt",
    )
    goo_probe(
        name = "nullable_intret_probe",
        src = "//examples:nullable_intret_probe.goo",
        expected = "//examples:nullable_intret_probe.expected.txt",
    )
    goo_probe(
        name = "nullable_nilcmp_probe",
        src = "//examples:nullable_nilcmp_probe.goo",
        expected = "//examples:nullable_nilcmp_probe.expected.txt",
    )
    goo_probe(
        name = "nullable_width_probe",
        src = "//examples:nullable_width_probe.goo",
        expected = "//examples:nullable_width_probe.expected.txt",
    )
    goo_probe(
        name = "pointer_probe",
        src = "//examples:pointer_probe.goo",
        expected = "//examples:pointer_probe.expected.txt",
    )
    goo_probe(
        name = "pointer_write_probe",
        src = "//examples:pointer_write_probe.goo",
        expected = "//examples:pointer_write_probe.expected.txt",
    )
    goo_probe(
        name = "select_probe",
        src = "//examples:select_probe.goo",
        expected = "//examples:select_probe.expected.txt",
    )
    goo_probe(
        name = "strindex_probe",
        src = "//examples:strindex_probe.goo",
        expected = "//examples:strindex_probe.expected.txt",
    )
    goo_probe(
        name = "switch_probe",
        src = "//examples:switch_probe.goo",
        expected = "//examples:switch_probe.expected.txt",
    )
    goo_probe(
        name = "unbuffered_probe",
        src = "//examples:unbuffered_probe.goo",
        expected = "//examples:unbuffered_probe.expected.txt",
    )
